/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Reservation = IDL.Record({
  'date' : IDL.Text,
  'specialRequests' : IDL.Opt(IDL.Text),
  'time' : IDL.Text,
  'guestName' : IDL.Text,
  'partySize' : IDL.Nat,
  'phoneNumber' : IDL.Text,
});

export const idlService = IDL.Service({
  'createReservation' : IDL.Func([Reservation], [IDL.Nat], []),
  'deleteReservation' : IDL.Func([IDL.Nat], [], []),
  'getAllReservations' : IDL.Func([], [IDL.Vec(Reservation)], ['query']),
  'getReservation' : IDL.Func([IDL.Nat], [Reservation], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Reservation = IDL.Record({
    'date' : IDL.Text,
    'specialRequests' : IDL.Opt(IDL.Text),
    'time' : IDL.Text,
    'guestName' : IDL.Text,
    'partySize' : IDL.Nat,
    'phoneNumber' : IDL.Text,
  });
  
  return IDL.Service({
    'createReservation' : IDL.Func([Reservation], [IDL.Nat], []),
    'deleteReservation' : IDL.Func([IDL.Nat], [], []),
    'getAllReservations' : IDL.Func([], [IDL.Vec(Reservation)], ['query']),
    'getReservation' : IDL.Func([IDL.Nat], [Reservation], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };